# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ac0405c2010205cb9027074bb1d62a6419d35915a7dea03cfd41cb7f6cdb02eb380fc7907280c167e1313c51fd41895a51173ffd2f60d49d321e4a06ce9d59

test:
  secret_key_base: 8f82f695e9f16b5418eddac30216284ce6c0bf73a0bbf91661dbfef2651f79d640125998df7469b9a69ab7faa8cb719e606cb100c557ae084eab6c2c1c8b52d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
